### ISSUE TITLE
ebuku--search-helper: Args out of range: "   # ", 6155, 6171

### ISSUE THREAD

**Issue by idmyn** [flexibeast/ebuku#16]
Hello again 😅

This isn't a disastrous issue, but I'm consistently finding that the first time I call `M-x ebuku` I get the above error in `*Messages*` (debugger output below). It opens the `*Ebuku*` buffer in the background, but doesn't open it. If I manually open the `*Ebuku*` buffer I can see all my bookmarks listed there. If I call `ebuku` again, then the buffer is opened without error. 

What's going on here?

Thanks!

```
Debugger entered--Lisp error: (args-out-of-range "   # " 6155 6171)
  match-string(1 "   # ")
  ebuku--search-helper("--print" "[all]" "-1000" "")
  ebuku-show-all()
  ebuku()
  funcall-interactively(ebuku)
  call-interactively(ebuku record nil)
  command-execute(ebuku record)
  counsel-M-x-action("ebuku")
```

**Comment by flexibeast** [comment]
Not disastrous, but clearly not satisfactory behaviour. :-)

Could you please `M-x toggle-debug-on-error` before your first `M-x ebuku`? That should then take you to the line in `ebuku.el` where the error is occurring.

**Comment by idmyn** [comment]
The code block at the bottom of my initial comment was the output of `M-x toggle-debug-on-error`

**Comment by flexibeast** [comment]
Ah, sorry. Basically what i need is to find the actual *line* on which the error is occurring, because `ebuku--search-helper` has a number of calls to `match-string`, and i need to find which one is producing the error.

Please open `ebuku.el`, move point to the `ebuku--search-helper` function, then instrument that function via `C-u M-C-x`. When you call `M-x ebuku`, that should take you to the source, showing the line about to be executed; at this point, press `g`. The code should then execute until the point at which the error occurs.

**Comment by idmyn** [comment]
Ooh, very cool! Thanks for explaining that process :)

It brought me to line 519.

**Comment by flexibeast** [comment]
Thanks. :-)

Could you please try changing the `\\(.+\\)` on line 518 to `\\(.*\\)`, reevaluating `ebuku--search-helper` with `C-M-x`, and restarting Ebuku to see if that fixes the problem?

**Comment by idmyn** [comment]
Yup, that's done the trick!

What was the problem, out of interest? Do I have some malformed tags?

**Comment by flexibeast** [comment]
Excellent. :-) i just pushed the fix. Thanks for helping me track down the problem!

It looks like at least one of your bookmarks had an empty tag field - the previous `ebuku.el` code incorrectly assumed that if a tag field is present, it must be non-empty.
