### ISSUE TITLE
Cannot handle line breaks in comment/description field

### ISSUE THREAD

**Issue by dppdppd** [flexibeast/ebuku#22]
If a bookmark has a description with a line break, ebuku fails with the error

Match-string: Args out of range: "<2nd line>", 5, 22

Repro:

1. add a comment with a line break using buku -w
2. eval ebuku-refresh

**Comment by flexibeast** [comment]
Thanks for the report! i believe this is now fixed via https://github.com/flexibeast/ebuku/commit/fa3f29fdf7c871c4eadf43c36ccc2e207116e5c3; can you please check?

**Comment by dppdppd** [comment]
Thanks for the quick response.

However, now I'm hitting this:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil buku-index "3005" data nil face ebuku-comment-face)
  ebuku--search-helper("--print" "[all]" "-1000" "")

Looking at 3005, the description has double-quotes in it.

Nope. A clean test shows ebuku handles quotes just fine.

**Comment by dppdppd** [comment]
The issue seems to be empty lines.

Repro:
buku -a google.com
buku -w 1

enter a few line breaks
save

ebuku-refresh

**Comment by flexibeast** [comment]
i'm unable to reproduce this, after trying various combinations of:

* all empty lines in the comment;
* mixtures of empty and non-empty lines;
* with and without tags;
* adding a bookmark directly via buku or indirectly via Ebuku. 

Can you reproduce the issue in a completely fresh instance of Emacs / the Emacs daemon?

**Comment by dppdppd** [comment]
I started with a clean emacs install in a docker container and worked my way back.

The issue has something to do with doom emacs compilation. Evaluating ebuku.el in my 'broken' emacs makes it work again.

I've gone through enough variations of variables tonight to suspect that this will repro it:

1. Install doom emacs
2. add `(package! ebuku)` to packages.el
3. create a bookmark with an empty line
4. `(ebuku)`

**Comment by flexibeast** [comment]
i created a new account on my system, and installed Doom from within that. i added `(package! ebuku)` to `packages.el` and `doom sync`d; Ebuku was succesfully installed. After using `buku` to create bookmarks with a comment containing a blank line, a blank line in-between two non-blank lines, and a blank line followed by two non-blank lines, Ebuku worked without error(s). So, sorry, but i'm unable to reproduce.

What does `doom doctor` report? Are you sure there aren't stale `.elc` files needing to a `doom clean`? At this stage there seems to be a problem specific to your setup, rather than with either Ebuku or Doom.

**Comment by dppdppd** [comment]
You're right. I did the same and it worked.

Wiping .emacs.d and rebuilding it fixed the issue.

Thanks for the help!

**Comment by flexibeast** [comment]
Great! You're welcome. :-)
