### ISSUE TITLE
Prompt for the URL first

### ISSUE THREAD

**Issue by rakanalh** [flexibeast/ebuku#7]
Looking at the code:
https://github.com/flexibeast/ebuku/blob/32ea7e09ce467a768c0ea3441472d19b40b2e4b7/ebuku.el#L415-L418

I can see that ebuku prompts for the title first. As far as i could see, entering the URL alone would enable buku to extract the title automatically from the URL so it would be a great improvement if i can just enter the URL first and press enter for the next 3 prompts or if i can set something like `(setq ebuku-prompt-url-only t)`

Thanks

**Comment by flexibeast** [comment]
Yes, i prefer this, as in my experience many Web sites have unhelpfully undescriptive titles (e.g. "A change in perspective") which make it difficult to search for articles in the future. i've also found that sometimes Buku fails to retrieve titles due to network connectivity issues (either between me and the server, or at the server itself).

That said, i think i'll add an option to support this. Because of the preceding, i'm slightly concerned about making it the default, but my overall feeling is that it probably should be.

**Comment by flexibeast** [comment]
Addressed by https://github.com/flexibeast/ebuku/commit/c31954ea95dd24d6706336826de7b547e035f7b9; closing.
